version: "3.7"
services:
  app:
    build:
      args:
        user: bruno
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: series
    container_name: series-app
    restart: unless-stopped
    working_dir: /var/www/
    command: >-
      sh -c "
        apk add php8-pecl-xdebug && composer install ;\
        cp .docker/php.ini-development /etc/php8/php.ini ;\
        cp .docker/xdebug.ini /etc/php8/conf.d/50_xdebug.ini ;\
        php artisan serve --host 0.0.0.0 --port 80"
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - rede-series

  nginx:
    image: nginx:alpine
    container_name: series-nginx
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - rede-series

networks:
  rede-series:
    driver: bridge